package lk.ijse.cafe.util;

public enum Routs {
    MANAGER,Item,STOKE,DASHBORAD,EMPLOYE,PLACE_ORDER,MAIN,SALAD,DESSERT,BEVERAGE,NIGHT_MAIL,BREAKFAST,PLACE_STOKE,NEW,LIST_ITEM,LIST_EMPLOYEE,
    CASHIER,MANGER_CREATE,CASHIER_CREATE,EMPLOY_VIEW,SUPPLIER,STOKEITEMS


}
